// Code generated by MockGen. DO NOT EDIT.
// Source: filter.go
//
// Generated by this command:
//
//	mockgen -source filter.go -package=vmi -destination=generated_mock_filter.go
//

// Package vmi is a generated GoMock package.
package vmi

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "kubevirt.io/api/core/v1"
)

// MockVMIFilter is a mock of VMIFilter interface.
type MockVMIFilter struct {
	ctrl     *gomock.Controller
	recorder *MockVMIFilterMockRecorder
	isgomock struct{}
}

// MockVMIFilterMockRecorder is the mock recorder for MockVMIFilter.
type MockVMIFilterMockRecorder struct {
	mock *MockVMIFilter
}

// NewMockVMIFilter creates a new mock instance.
func NewMockVMIFilter(ctrl *gomock.Controller) *MockVMIFilter {
	mock := &MockVMIFilter{ctrl: ctrl}
	mock.recorder = &MockVMIFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVMIFilter) EXPECT() *MockVMIFilterMockRecorder {
	return m.recorder
}

// Matches mocks base method.
func (m *MockVMIFilter) Matches(vmi *v1.VirtualMachineInstance) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Matches", vmi)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Matches indicates an expected call of Matches.
func (mr *MockVMIFilterMockRecorder) Matches(vmi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Matches", reflect.TypeOf((*MockVMIFilter)(nil).Matches), vmi)
}
