// Code generated by MockGen. DO NOT EDIT.
// Source: finder.go
//
// Generated by this command:
//
//	mockgen -source finder.go -package=process -destination=generated_mock_finder.go
//

// Package process is a generated GoMock package.
package process

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "kubevirt.io/api/core/v1"
)

// MockVmiProcessFinder is a mock of VmiProcessFinder interface.
type MockVmiProcessFinder struct {
	ctrl     *gomock.Controller
	recorder *MockVmiProcessFinderMockRecorder
	isgomock struct{}
}

// MockVmiProcessFinderMockRecorder is the mock recorder for MockVmiProcessFinder.
type MockVmiProcessFinderMockRecorder struct {
	mock *MockVmiProcessFinder
}

// NewMockVmiProcessFinder creates a new mock instance.
func NewMockVmiProcessFinder(ctrl *gomock.Controller) *MockVmiProcessFinder {
	mock := &MockVmiProcessFinder{ctrl: ctrl}
	mock.recorder = &MockVmiProcessFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVmiProcessFinder) EXPECT() *MockVmiProcessFinderMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockVmiProcessFinder) Find(vmi *v1.VirtualMachineInstance) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", vmi)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockVmiProcessFinderMockRecorder) Find(vmi any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockVmiProcessFinder)(nil).Find), vmi)
}

// Info mocks base method.
func (m *MockVmiProcessFinder) Info() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info")
	ret0, _ := ret[0].(string)
	return ret0
}

// Info indicates an expected call of Info.
func (mr *MockVmiProcessFinderMockRecorder) Info() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockVmiProcessFinder)(nil).Info))
}
