// Code generated by MockGen. DO NOT EDIT.
// Source: filter.go
//
// Generated by this command:
//
//	mockgen -source filter.go -package=process -destination=generated_mock_filter.go
//

// Package process is a generated GoMock package.
package process

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProcessFilter is a mock of ProcessFilter interface.
type MockProcessFilter struct {
	ctrl     *gomock.Controller
	recorder *MockProcessFilterMockRecorder
	isgomock struct{}
}

// MockProcessFilterMockRecorder is the mock recorder for MockProcessFilter.
type MockProcessFilterMockRecorder struct {
	mock *MockProcessFilter
}

// NewMockProcessFilter creates a new mock instance.
func NewMockProcessFilter(ctrl *gomock.Controller) *MockProcessFilter {
	mock := &MockProcessFilter{ctrl: ctrl}
	mock.recorder = &MockProcessFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessFilter) EXPECT() *MockProcessFilterMockRecorder {
	return m.recorder
}

// Info mocks base method.
func (m *MockProcessFilter) Info() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info")
	ret0, _ := ret[0].(string)
	return ret0
}

// Info indicates an expected call of Info.
func (mr *MockProcessFilterMockRecorder) Info() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockProcessFilter)(nil).Info))
}

// Matches mocks base method.
func (m *MockProcessFilter) Matches(p *ProcessInfo) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Matches", p)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Matches indicates an expected call of Matches.
func (mr *MockProcessFilterMockRecorder) Matches(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Matches", reflect.TypeOf((*MockProcessFilter)(nil).Matches), p)
}
